# SPDX-License-Identifier: Apache-2.0
"""The generated pages say what the wiring says, complete in place, in the form the docs site needs.

Run: uv run --no-project --with pytest --with fonttools==4.65.0 pytest docs/wiring/tt-fpga
"""

import math
import re

import picture
import tables
import wiring

W = wiring.WIRING
FILES = tables.build()
WIRE_PAGES = ("tt-fpga-cables.md", "tt-fpga-pins-ui-uo.md", "tt-fpga-pins-uio-uart.md", "tt-fpga-pins-other.md")


def table_rows(text):
    """Every table of a page, each as a list of rows of cells (the header row first, the rule left out)."""
    found, rows = [], []
    for line in [*text.splitlines(), ""]:
        if line.startswith("|"):
            if not set(line) <= set("|-"):
                rows.append([cell.strip() for cell in line.strip("|").split(" | ")])
        elif rows:
            found.append(rows)
            rows = []
    return found


def sheets(text):
    """A cautious estimate of the printed A4 sheets a page of this text takes: 45 lines of 95 characters to a
    sheet, a table row or a paragraph wrapped at that width with a blank line after it, a picture 25 lines."""
    lines = 0
    for block in text.split("\n\n"):
        for line in block.splitlines():
            lines += 25 if "](tt-fpga-pmod-cables" in line else math.ceil(max(len(line), 1) / 95)
        lines += 1
    return lines / 45


def test_every_page_starts_with_the_generators_banner_and_names_this_generator():
    for name, text in FILES.items():
        assert text.startswith("<!-- Generated by fpgas.online-test-designs docs/wiring/tt-fpga/gen.py"), name
        assert text.splitlines()[1] == "", name


def test_every_wire_page_says_first_who_it_is_for_and_what_hardware():
    for name in WIRE_PAGES:
        first = FILES[name].splitlines()[2]
        assert first.startswith("For the person at the bench with a Tiny Tapeout demo board"), name
        assert "Raspberry Pi carrying a Digilent Pmod HAT" in first, name


def test_no_table_is_wider_than_six_columns():
    for name, text in FILES.items():
        for rows in table_rows(text):
            assert len(rows[0]) <= 6, (name, rows[0])
            assert all(len(r) == len(rows[0]) for r in rows), (name, rows[0])


def test_no_page_comes_near_five_printed_sheets():
    for name, text in FILES.items():
        assert sheets(text) <= 4, (name, sheets(text))


def test_a_wire_table_has_the_chain_in_order_and_every_wire_of_its_group_once():
    for page, groups in (("tt-fpga-pins-ui-uo.md", ("ui_in", "uo_out")), ("tt-fpga-pins-uio-uart.md", ("uio",))):
        wire_tables = [t for t in table_rows(FILES[page]) if t[0][-1] == "Checked"]
        assert len(wire_tables) == len(groups)
        for rows, group in zip(wire_tables, groups, strict=True):
            assert rows[0] == ["iCE40 pin", "Signal", "Demo board", "Pmod HAT", "Pi GPIO", "Checked"]
            assert [r[1] for r in rows[1:]] == [f"`{group}[{bit}]`" for bit in range(8)]
            for row, w in zip(rows[1:], W.of_group(group), strict=True):
                header = W.headers[w.header]["name"]
                assert row[0] == str(w.fpga_pin)
                assert row[2] == f"{header} pin {w.pin}" and row[3] == f"{w.port} pin {w.pin}"
                assert row[4] == f"GPIO{w.gpio}" + (" (shared)" if W.shares(w) else "")
                assert row[5] == ("measured" if W.measured(w) else "from the design")


def test_the_rows_the_hand_written_page_had_are_still_what_the_tables_say():
    """A few rows of the page this generator replaced, as it stood at commit ef38e22."""
    page = FILES["tt-fpga-pins-ui-uo.md"] + FILES["tt-fpga-pins-uio-uart.md"]
    assert "| 13 | `ui_in[0]` | INPUT pin 1 | JA pin 1 | GPIO8 | measured |" in page
    assert "| 21 | `ui_in[3]` | INPUT pin 4 | JA pin 4 | GPIO11 (shared) | from the design |" in page
    assert "| 48 | `uo_out[7]` | OUTPUT pin 10 | JC pin 10 | GPIO6 | measured |" in page
    assert "| 12 | `uio[7]` | BIDIR pin 10 | JB pin 10 | GPIO2 | measured |" in page
    assert "| 45 | `uo_out[4]` | serial data out of the design (its TX) | OUTPUT pin 7 | JC pin 7 | GPIO4 |" in page


def test_a_page_with_a_wire_table_repeats_the_picture_and_how_to_find_the_header_in_place():
    for name in WIRE_PAGES:
        text = FILES[name]
        shown = re.findall(r"\[!\[[^\]]+\]\((tt-fpga-[a-z-]*)\.png\)\]\(\1\.svg\)", text)
        if name == "tt-fpga-pins-other.md":  # its picture is the display's, in its own section
            assert shown == [picture.DISPLAY], name
        else:
            assert shown and set(shown) <= set(picture.PICTURES), name
        assert "**Finding the headers.**" in text, name
        assert "pin 1 to pin 1" in text, name
    # the picture of each page picks out the headers that page is about
    assert "tt-fpga-pmod-cables-ui-uo.png" in FILES["tt-fpga-pins-ui-uo.md"]
    assert "(tt-fpga-pmod-cables.png)" in FILES["tt-fpga-pins-uio-uart.md"]


def test_a_measured_wire_has_its_dates_under_its_table_and_its_place_once_on_the_sources_page():
    (m,) = W.measurements
    line = (
        "*measured*: read on boards on 29 September 2026 and 4 October 2026; "
        "for where and how, see [Sources](tt-fpga-sources.md)"
    )
    for name in ("tt-fpga-cables.md", "tt-fpga-pins-ui-uo.md", "tt-fpga-pins-uio-uart.md", "tt-fpga-pins-other.md"):
        text = FILES[name]
        assert line in text, name
        assert m.where not in text and "sw2" not in text, name
    for name in ("tt-fpga-cables.md", "tt-fpga-pins-ui-uo.md", "tt-fpga-pins-uio-uart.md"):
        text = FILES[name]
        assert "*from the design*: not read on a board;" in text and "not measured by us" in text, name
    sources = FILES["tt-fpga-sources.md"]
    assert sources.count(m.where) == 1 and m.when in sources and tables.linked_paths(m.record) in sources
    assert "the host at sw2 p34 was not powered either time" in sources
    assert "test_identify_pmod_pins.py" in m.record and "`8987ede`" in m.record and "`ef38e22`" in m.record


def test_the_serial_ports_table_says_which_of_its_two_wires_is_measured():
    text = FILES["tt-fpga-pins-uio-uart.md"]
    assert "`ui_in[3]` is from the design and `uo_out[4]` is measured." in text


def test_the_pin_1_warning_is_under_every_picture():
    warning = (
        "**Pin 1 on the picture.** Pin 1 (gold) is drawn where Tiny Tapeout's drawing of the demo board puts it, "
        "not checked by us: seen from above, Pmod edge toward you, the right-hand end of the row farther from the "
        "edge. The HAT's ports are drawn the same way; where their printed 1 is has not been checked by us. Find "
        "pin 1 on each connector by its marking before plugging a cable in. A 2x6 cable turned round puts 3.3 V "
        "on signal pins."
    )
    for name in WIRE_PAGES:  # the display's picture is no picture of cables, so has no pin 1 to warn about
        text = FILES[name]
        pictures = text.count("(tt-fpga-pmod-cables")
        if name == "tt-fpga-pins-other.md":
            assert pictures == 0 and warning not in text, name
            continue
        assert text.count(warning) == pictures // 2 >= 1, name  # each picture names its PNG and its SVG
        for shown in re.finditer(r"tt-fpga-pmod-cables[a-z-]*\.svg\)\n\n", text):
            assert text[shown.end() :].startswith(warning), name


def test_the_cables_page_lists_what_the_makers_say_one_fact_to_a_bullet_under_three_leads():
    text = FILES["tt-fpga-cables.md"]
    assert "**From the makers' documents, not checked by us on a board.**" in text
    leads = ["**The demo board's sockets**", "**The Pmod HAT's ports**", "**The cables**"]
    assert [text.index(lead) for lead in leads] == sorted(text.index(lead) for lead in leads)
    bullets = [line for line in text.splitlines() if line.startswith("- ")]
    order = list(tables.MAKERS_LISTS)
    listed = sorted((f for f in W.facts.values() if f["group"] in order), key=lambda f: order.index(f["group"]))
    assert bullets == [f"- {f['says']}." for f in listed]
    assert all(bullet.count(". ") <= 1 for bullet in bullets)  # one or two sentences each
    assert "- A twelve-wire straight cable joins the two boards' 3.3 V supplies." in bullets
    assert (
        "- What cable is fitted on our boards, and whether its pins 6 and 12 are connected, is not recorded; "
        "asked on 6 October 2026."
    ) in bullets
    assert "the boards shown as fpga-1 and fpga-3 on tinytapeout.fpgas.online on 6 October 2026" in text
    assert "mirrored" not in text  # Digilent's sentence on numbering is on the sources page only
    assert "measured, except the wires on shared GPIOs" in text


def test_a_pin_table_page_points_at_the_cables_page_instead_of_repeating_the_makers_list():
    for name in ("tt-fpga-pins-ui-uo.md", "tt-fpga-pins-uio-uart.md", "tt-fpga-pins-other.md"):
        text = FILES[name]
        assert tables.SEE_CABLES.strip() in text, name
        assert "see [the cables page](tt-fpga-cables.md)" in text, name
        assert not [line for line in text.splitlines() if line.startswith("- ")], name
        assert "From the makers' documents" not in text and "rainbow" not in text, name
        assert "are printed INPUT (`ui_in`), BIDIR (`uio`) and OUTPUT (`uo_out`)." in text, name


def test_the_serial_ports_test_has_its_date_on_the_page_and_its_place_on_the_sources_page():
    text = FILES["tt-fpga-pins-uio-uart.md"]
    assert "That test passed on 2 October 2026; for where, see [Sources](tt-fpga-sources.md)." in text
    where = tables.linked_paths(W.uart["checked"]["where"])
    assert f"It passed on 2 October 2026 on {where}." in FILES["tt-fpga-sources.md"]


def test_every_makers_fact_has_its_source_on_the_sources_page_and_none_is_called_verified():
    text = FILES["tt-fpga-sources.md"]
    for fact in W.facts.values():
        assert f"- {fact['says']}: {tables.linked_paths(fact['source'])}." in text, fact["key"]
    assert "mirrored between the host connector and the peripheral board connector" in text
    assert "github.com/TinyTapeout/tt-demo-pcb" in text and text.count("read from a copy on 6 October 2026") >= 3
    assert "verified by us on" not in text.replace("not verified by us on", "")


def test_the_ui_in_page_says_the_dip_switches_are_there_and_that_their_setting_is_not_recorded():
    text = FILES["tt-fpga-pins-ui-uo.md"]
    assert "The demo board's DIP switches are on these signals too" in text
    assert "How the switches must be set while the Raspberry Pi drives these signals is not recorded." in text


def test_the_shared_gpios_are_explained_on_every_page_that_has_one():
    for name in ("tt-fpga-cables.md", "tt-fpga-pins-ui-uo.md", "tt-fpga-pins-uio-uart.md"):
        text = FILES[name]
        assert "**Shared GPIOs.**" in text, name
        assert "GPIO10 is JA pin 2 and JB pin 2 (`ui_in[1]` and `uio[1]`)" in text, name
    assert "Shared GPIOs" not in FILES["tt-fpga-pins-other.md"]  # uo_out shares nothing


def test_the_streaming_rule_is_on_every_page_that_mentions_loading():
    """As a rule, and then only the fact this repository can stand behind: its own loader and tests."""
    for name, text in FILES.items():
        if re.search(r"\bload(s|ed|ing|er)?\b", text, re.I) and name != "tt-fpga-sources.md":
            assert tables.STREAMING in text, name
    assert tables.STREAMING in FILES["tt-fpga-pins-other.md"] and tables.STREAMING in FILES["tt-fpga-cables.md"]
    assert tables.STREAMING.startswith("**The rule here: an FPGA on a demo board is loaded by streaming only**")
    assert "no code of ours may write, replace or delete a file on a demo board" in tables.STREAMING
    assert "The loader and the tests in this repository do not" in tables.STREAMING
    assert "No code of ours writes" not in "".join(FILES.values())


def test_the_page_of_other_pins_says_there_is_no_flash_and_that_no_cable_carries_them():
    text = FILES["tt-fpga-pins-other.md"]
    assert "has no SPI flash" in text
    assert text.count("no cable carries them, and the Raspberry Pi cannot reach them") == 2
    assert "| 16 | `SPI_SS` |" in text and "| GPIO6 | clock |" in text
    assert "is not recorded in this repository and has not been measured by us" in text
    assert "| dot | `uo_out[7]` | 48 | OUTPUT pin 10 | JC pin 10 | GPIO6 |" in text
    assert "| 37 | `rst_n` | the design's reset: low resets it | GPIO14 (not verified by us) |" in text
    assert "| 20 | `clk_rp2040` | the clock into the design, made by the microcontroller: 50 MHz | GPIO16 |" in text
    assert "| 39 | `rgb_led.r` | red of the three-colour LED: low lights it | not recorded |" in text
    assert "| none |" not in text and "every Pmod test" not in text
    assert "where a is, and which way round the ring that order goes, is not recorded and not verified by us" in text
    assert "| `uio[0]` to `uio[7]` | GPIO25 to GPIO32 |" in text


def test_the_sources_page_prints_every_source_and_says_what_nobody_checked():
    text = FILES["tt-fpga-sources.md"]
    for claim, source in tables.sources().items():
        assert f"- {claim}: {tables.linked_paths(source)}." in text
    assert set(W.sources) < set(tables.sources())  # the measurements add their own entries
    assert "{" not in text  # no placeholder left unfilled
    assert text.count("not verified by us") >= 5 and "not measured by us" in text
    assert "commit `ef38e22`" in text and "29 September 2026" in text


def test_the_words_follow_the_writing_rules():
    """Nothing private or drifting is named: not the upstream gateway, no home directory, no address; dates are
    day first; a machine is named by where it was seen on a day, never as a host name."""
    for name, text in FILES.items():
        low = text.lower()
        for banned in ("ten64", "/home/", "~/", "10.21.", "pi-sw", "mithis", "color", "center"):
            assert banned not in low, (name, banned)
        assert not re.search(r"\b20\d\d-\d\d-\d\d\b", text), name  # dates are written out, day first
        for seen in re.findall(r"[^.;]*sw2 p\d+[^.;]*", text):
            assert "seen at welland's sw2" in text, name
            assert "that day" in seen or "those days" in seen or "either time" in seen, (name, seen)


def test_every_other_page_is_a_markdown_link_to_its_sibling_fragment_not_a_file_name_in_backticks():
    """The docs site includes each fragment with :relative-docs: tt-fpga-, which rewrites a link to a sibling."""
    for name, text in FILES.items():
        assert not re.search(r"`tt-fpga-[a-z-]+\.md`", text), name
        for target in re.findall(r"\]\((tt-fpga-[a-z-]+\.md)\)", text):
            assert target in FILES and target != name, (name, target)
    assert "[Sources](tt-fpga-sources.md)" in FILES["tt-fpga-cables.md"]
    assert "[the cables page](tt-fpga-cables.md)" in FILES["tt-fpga-pins-other.md"]


def test_the_files_of_this_repository_named_on_the_sources_page_are_links_to_them_on_github():
    text = FILES["tt-fpga-sources.md"]
    assert not re.search(r"(?<!\[)`(?:docs|designs)/[^`\s]+`(?!\]\()", text)
    base = "https://github.com/fpgas-online/fpgas.online-test-designs/blob/main/"
    assert f"[`docs/hardware/pmod-tt.md`]({base}docs/hardware/pmod-tt.md)" in text
    assert f"[`designs/_host/tt_fpga_program.py`]({base}designs/_host/tt_fpga_program.py)" in text


def test_the_display_section_shows_the_display_not_the_cable_diagram():
    text = FILES["tt-fpga-pins-other.md"]
    section = text.split("### The seven-segment display")[1].split("### The clock")[0]
    assert f"({picture.DISPLAY}.png)]({picture.DISPLAY}.svg)" in section
    assert "tt-fpga-pmod-cables" not in section
