# SPDX-License-Identifier: Apache-2.0
"""The generated pages say what the wiring says, complete in place, in the form the docs site needs.

Run: uv run --no-project --with pytest --with fonttools==4.65.0 pytest docs/wiring/tt-fpga
"""

import math
import re

import picture
import tables
import wiring

W = wiring.WIRING
FILES = tables.build()
WIRE_PAGES = ("tt-fpga-cables.md", "tt-fpga-pins-ui-uo.md", "tt-fpga-pins-uio-uart.md", "tt-fpga-pins-other.md")


def table_rows(text):
    """Every table of a page, each as a list of rows of cells (the header row first, the rule left out)."""
    found, rows = [], []
    for line in [*text.splitlines(), ""]:
        if line.startswith("|"):
            if not set(line) <= set("|-"):
                rows.append([cell.strip() for cell in line.strip("|").split(" | ")])
        elif rows:
            found.append(rows)
            rows = []
    return found


def sheets(text):
    """A cautious estimate of the printed A4 sheets a page of this text takes: 45 lines of 95 characters to a
    sheet, a table row or a paragraph wrapped at that width with a blank line after it, a picture 25 lines."""
    lines = 0
    for block in text.split("\n\n"):
        for line in block.splitlines():
            lines += 25 if "](tt-fpga-pmod-cables" in line else math.ceil(max(len(line), 1) / 95)
        lines += 1
    return lines / 45


def test_every_page_starts_with_the_generators_banner_and_names_this_generator():
    for name, text in FILES.items():
        assert text.startswith("<!-- Generated by fpgas.online-test-designs docs/wiring/tt-fpga/gen.py"), name
        assert text.splitlines()[1] == "", name


def test_every_wire_page_says_first_who_it_is_for_and_what_hardware():
    for name in WIRE_PAGES:
        first = FILES[name].splitlines()[2]
        assert first.startswith("For the person at the bench with a Tiny Tapeout demo board"), name
        assert "Raspberry Pi carrying a Digilent Pmod HAT" in first, name


def test_no_table_is_wider_than_six_columns():
    for name, text in FILES.items():
        for rows in table_rows(text):
            assert len(rows[0]) <= 6, (name, rows[0])
            assert all(len(r) == len(rows[0]) for r in rows), (name, rows[0])


def test_no_page_comes_near_five_printed_sheets():
    for name, text in FILES.items():
        assert sheets(text) <= 3, (name, sheets(text))


def test_a_wire_table_has_the_chain_in_order_and_every_wire_of_its_group_once():
    for page, groups in (("tt-fpga-pins-ui-uo.md", ("ui_in", "uo_out")), ("tt-fpga-pins-uio-uart.md", ("uio",))):
        wire_tables = [t for t in table_rows(FILES[page]) if t[0][-1] == "Checked"]
        assert len(wire_tables) == len(groups)
        for rows, group in zip(wire_tables, groups, strict=True):
            assert rows[0] == ["iCE40 pin", "Signal", "Demo board", "Pmod HAT", "Pi GPIO", "Checked"]
            assert [r[1] for r in rows[1:]] == [f"`{group}[{bit}]`" for bit in range(8)]
            for row, w in zip(rows[1:], W.of_group(group), strict=True):
                header = W.headers[w.header]["name"]
                assert row[0] == str(w.fpga_pin)
                assert row[2] == f"{header} pin {w.pin}" and row[3] == f"{w.port} pin {w.pin}"
                assert row[4] == f"GPIO{w.gpio}" + (" (shared)" if W.shares(w) else "")
                assert row[5] == ("measured" if W.measured(w) else "from the design")


def test_the_rows_the_hand_written_page_had_are_still_what_the_tables_say():
    """A few rows of the page this generator replaced, as it stood at commit ef38e22."""
    page = FILES["tt-fpga-pins-ui-uo.md"] + FILES["tt-fpga-pins-uio-uart.md"]
    assert "| 13 | `ui_in[0]` | Input pin 1 | JA pin 1 | GPIO8 | measured |" in page
    assert "| 21 | `ui_in[3]` | Input pin 4 | JA pin 4 | GPIO11 (shared) | from the design |" in page
    assert "| 48 | `uo_out[7]` | Output pin 10 | JC pin 10 | GPIO6 | measured |" in page
    assert "| 12 | `uio[7]` | Bidirectional pin 10 | JB pin 10 | GPIO2 | measured |" in page
    assert "| 45 | `uo_out[4]` | serial data out of the design (its TX) | Output pin 7 | JC pin 7 | GPIO4 |" in page


def test_a_page_with_a_wire_table_repeats_the_picture_and_how_to_find_the_header_in_place():
    for name in WIRE_PAGES:
        text = FILES[name]
        shown = re.findall(r"\[!\[[^\]]+\]\((tt-fpga-pmod-cables[a-z-]*)\.png\)\]\(\1\.svg\)", text)
        assert shown and set(shown) <= set(picture.PICTURES), name
        assert "**Finding the headers.**" in text and "**Not checked by us against a board:**" in text, name
        assert "pin 1 to pin 1" in text, name
    # the picture of each page picks out the headers that page is about
    assert "tt-fpga-pmod-cables-ui-uo.png" in FILES["tt-fpga-pins-ui-uo.md"]
    assert "tt-fpga-pmod-cables-uo.png" in FILES["tt-fpga-pins-other.md"]
    assert "(tt-fpga-pmod-cables.png)" in FILES["tt-fpga-pins-uio-uart.md"]


def test_a_measured_wire_has_its_date_and_place_under_its_table_and_an_unmeasured_one_says_so():
    (m,) = W.measurements
    for name in ("tt-fpga-cables.md", "tt-fpga-pins-ui-uo.md", "tt-fpga-pins-uio-uart.md"):
        text = FILES[name]
        assert m.when in text and m.where in text, name
        assert "*from the design*: not read on a board;" in text and "not measured by us" in text, name


def test_the_shared_gpios_are_explained_on_every_page_that_has_one():
    for name in ("tt-fpga-cables.md", "tt-fpga-pins-ui-uo.md", "tt-fpga-pins-uio-uart.md"):
        text = FILES[name]
        assert "**Shared GPIOs.**" in text, name
        assert "GPIO10 is JA pin 2 and JB pin 2 (`ui_in[1]` and `uio[1]`)" in text, name
    assert "Shared GPIOs" not in FILES["tt-fpga-pins-other.md"]  # uo_out shares nothing


def test_the_streaming_rule_is_on_every_page_that_mentions_loading():
    for name, text in FILES.items():
        if re.search(r"\bload(s|ed|ing|er)?\b", text, re.I) and name != "tt-fpga-sources.md":
            assert "**The FPGA is loaded by streaming only.**" in text, name
            assert "No code of ours writes, replaces or deletes a file on a Tiny Tapeout demo board." in text, name
    assert tables.STREAMING in FILES["tt-fpga-pins-other.md"] and tables.STREAMING in FILES["tt-fpga-cables.md"]


def test_the_page_of_other_pins_says_there_is_no_flash_and_that_no_cable_carries_them():
    text = FILES["tt-fpga-pins-other.md"]
    assert "has no SPI flash" in text
    assert text.count("no cable carries them, and the Raspberry Pi cannot reach them") == 2
    assert "| 16 | `SPI_SS` |" in text and "| GPIO6 | clock |" in text
    assert "is not recorded in this repository and has not been measured by us" in text
    assert "| dot | `uo_out[7]` | 48 | Output pin 10 | JC pin 10 | GPIO6 |" in text
    assert "| 37 | `rst_n` | the design's reset: low resets it | GPIO14 (not verified by us) |" in text
    assert "| `uio[0]` to `uio[7]` | GPIO25 to GPIO32 |" in text


def test_the_sources_page_prints_every_source_and_says_what_nobody_checked():
    text = FILES["tt-fpga-sources.md"]
    for claim, source in tables.sources().items():
        assert f"- {claim}: {source}." in text
    assert set(W.sources) < set(tables.sources())  # the measurements add their own entries
    assert "{" not in text  # no placeholder left unfilled
    assert text.count("not verified by us") >= 5 and "not measured by us" in text
    assert "commit `ef38e22`" in text and "29 September 2026" in text


def test_the_words_follow_the_writing_rules():
    """Nothing private or drifting is named: not the upstream gateway, no home directory, no address; dates are
    day first; a machine is named by where it was seen on a day, never as a host name."""
    for name, text in FILES.items():
        low = text.lower()
        for banned in ("ten64", "/home/", "~/", "10.21.", "pi-sw", "mithis", "color", "center"):
            assert banned not in low, (name, banned)
        assert not re.search(r"\b20\d\d-\d\d-\d\d\b", text), name  # dates are written out, day first
        for seen in re.findall(r"sw2 p\d+[^.;]*", text):
            assert "seen at welland's sw2" in text and ("that day" in seen or "those days" in seen), (name, seen)
