"""openXC7 fixups for litex-boards platforms (designs/_shared/platform_fixups.py)."""

from pathlib import Path
from types import SimpleNamespace

import pytest
from litex.build.generic_platform import IOStandard, Subsignal
from litex_boards.platforms import digilent_arty, kosagi_fomu_evt, kosagi_netv2
from migen import ClockDomain

from designs._shared.platform_fixups import (
    constrain_openxc7_clocks,
    fix_openxc7_reduced_drive_iostandards,
    require_litex_boards_timing,
    require_timing,
)


def iostandards(resource):
    """Every IOStandard name in a resource tuple, including those inside its subsignals."""
    names = []
    for item in resource[2:]:
        if isinstance(item, IOStandard):
            names.append(item.name)
        elif isinstance(item, Subsignal):
            names += [c.name for c in item.constraints if isinstance(c, IOStandard)]
    return names


def ddram(platform):
    return next(r for r in platform.constraint_manager.available if r[0] == "ddram")


def test_netv2_ddram_is_reduced_drive_sstl15_to_begin_with():
    platform = kosagi_netv2.Platform(variant="a7-35", toolchain="openxc7")
    assert set(iostandards(ddram(platform))) == {"SSTL15_R", "DIFF_SSTL15_R", "LVCMOS15"}


def test_the_ddram_standards_become_ones_nextpnr_xilinx_knows():
    platform = kosagi_netv2.Platform(variant="a7-35", toolchain="openxc7")
    fix_openxc7_reduced_drive_iostandards(platform)
    assert set(iostandards(ddram(platform))) == {"SSTL15", "DIFF_SSTL15", "LVCMOS15"}


def test_the_other_constraints_are_kept():
    platform = kosagi_netv2.Platform(variant="a7-35", toolchain="openxc7")
    before = [repr(r) for r in platform.constraint_manager.available]
    fix_openxc7_reduced_drive_iostandards(platform)
    after = [repr(r).replace("SSTL15_R", "SSTL15") for r in platform.constraint_manager.available]
    assert after == [b.replace("SSTL15_R", "SSTL15") for b in before]


def test_the_board_definition_itself_is_not_changed():
    fix_openxc7_reduced_drive_iostandards(kosagi_netv2.Platform(variant="a7-35", toolchain="openxc7"))
    vivado = kosagi_netv2.Platform(variant="a7-35", toolchain="vivado")
    assert set(iostandards(ddram(vivado))) == {"SSTL15_R", "DIFF_SSTL15_R", "LVCMOS15"}


def test_each_pll_output_gets_its_own_period():
    platform = digilent_arty.Platform(variant="a7-35", toolchain="openxc7")
    sys, sys4x = ClockDomain("sys"), ClockDomain("sys4x")
    constrain_openxc7_clocks(platform, {sys: 80e6, sys4x: 320e6})
    assert platform.toolchain.clocks[sys.clk][0] == 12.5
    assert platform.toolchain.clocks[sys4x.clk][0] == 3.125


def test_vivado_builds_are_left_to_derive_their_own():
    platform = digilent_arty.Platform(variant="a7-35", toolchain="vivado")
    sys = ClockDomain("sys")
    constrain_openxc7_clocks(platform, {sys: 80e6})
    assert sys.clk not in platform.toolchain.clocks


def test_openxc7_builds_fail_when_timing_fails():
    platform = digilent_arty.Platform(variant="a7-35", toolchain="openxc7")
    seen = {}
    platform.toolchain.build = lambda *args, **kwargs: seen.update(kwargs)
    constrain_openxc7_clocks(platform, {ClockDomain("sys"): 80e6})
    platform.toolchain.build(platform, None, timingstrict=False)  # what LiteXArgumentParser passes by default
    assert seen["timingstrict"] is True


@pytest.mark.parametrize("freq", [0, -1])
def test_a_nonsense_frequency_is_refused(freq):
    platform = digilent_arty.Platform(variant="a7-35", toolchain="openxc7")
    with pytest.raises(ValueError):
        constrain_openxc7_clocks(platform, {ClockDomain("sys"): freq})


SCRIPT = """# Autogenerated by LiteX
set -e
yosys -l top.rpt top.ys
nextpnr-xilinx --json top.json --xdc top.xdc --fasm top.fasm --log top_nextpnr.log --seed 1  --freq 400
fasm2frames --part x top.fasm > top.frames
xc7frames2bit --frm_file top.frames --output_file top.bit
"""
MISSED = "ERROR: Max frequency for clock 'crg_clkout_buf0': 74.04 MHz (FAIL at 75.00 MHz)\n"


class _ScriptToolchain:
    """Stands in for LiteX's openXC7 toolchain: run_script() runs the build script in the build directory."""

    is_openxc7 = True
    _build_name = "top"

    def __init__(self, logs):
        self.logs = list(logs)  # what nextpnr logs on each run; None: the run succeeds
        self.scripts = []

    def build(self, *args, **kwargs):
        pass

    def finalize(self):
        pass

    def run_script(self, script):
        self.scripts.append(Path(script).read_text())
        log = self.logs.pop(0)
        if log is not None:
            Path("top_nextpnr.log").write_text(log)
            raise OSError("Error occured during Yosys/Nextpnr's script execution.")


def _strict(tmp_path, monkeypatch, logs):
    monkeypatch.chdir(tmp_path)
    (tmp_path / "build_top.sh").write_text(SCRIPT)
    tc = _ScriptToolchain(logs)
    platform = digilent_arty.Platform(variant="a7-35", toolchain="openxc7")
    platform.toolchain = tc
    platform.add_period_constraint = lambda *a, **k: None
    constrain_openxc7_clocks(platform, {ClockDomain("sys"): 75e6})
    return tc


def test_a_missed_clock_is_placed_again_with_the_next_seed(tmp_path, monkeypatch):
    tc = _strict(tmp_path, monkeypatch, [MISSED, None])
    tc.run_script("build_top.sh")
    assert len(tc.scripts) == 2
    assert "yosys" not in tc.scripts[1]  # synthesis is not repeated
    assert "--seed 2 " in tc.scripts[1] and "fasm2frames" in tc.scripts[1] and "xc7frames2bit" in tc.scripts[1]


def test_another_failure_is_not_retried(tmp_path, monkeypatch):
    tc = _strict(tmp_path, monkeypatch, ["ERROR: Unable to place cell 'x'\n"])
    with pytest.raises(OSError):
        tc.run_script("build_top.sh")
    assert len(tc.scripts) == 1


def test_it_gives_up_after_the_last_seed(tmp_path, monkeypatch):
    from designs._shared.platform_fixups import OPENXC7_TIMING_SEEDS

    tc = _strict(tmp_path, monkeypatch, [MISSED] * OPENXC7_TIMING_SEEDS)
    with pytest.raises(OSError, match="timing"):
        tc.run_script("build_top.sh")
    assert len(tc.scripts) == OPENXC7_TIMING_SEEDS


def test_nextpnr_logs_to_a_file_the_retry_can_read():
    platform = digilent_arty.Platform(variant="a7-35", toolchain="openxc7")
    tc = platform.toolchain

    class _Nextpnr:
        _pnr_opts = "--seed 1 "

    def finalize():
        tc._nextpnr = _Nextpnr()

    tc.finalize = finalize
    tc._build_name = "digilent_arty"
    constrain_openxc7_clocks(platform, {ClockDomain("sys"): 75e6})
    tc.finalize()
    assert "--log digilent_arty_nextpnr.log" in tc._nextpnr._pnr_opts


def test_a_second_call_adds_its_clocks_but_wraps_nothing_twice():
    platform = digilent_arty.Platform(variant="a7-35", toolchain="openxc7")
    tc = platform.toolchain

    class _Nextpnr:
        _pnr_opts = "--seed 1 "

    def finalize():
        tc._nextpnr = _Nextpnr()

    tc.finalize = finalize
    tc._build_name = "digilent_arty"
    sys, eth = ClockDomain("sys"), ClockDomain("eth")
    constrain_openxc7_clocks(platform, {sys: 75e6})
    constrain_openxc7_clocks(platform, {eth: 25e6})
    tc.finalize()
    assert tc._nextpnr._pnr_opts.count("--log ") == 1
    assert tc.clocks[eth.clk][0] == 40.0


def test_require_timing_on_openxc7_is_constrain_openxc7_clocks():
    platform = digilent_arty.Platform(variant="a7-35", toolchain="openxc7")
    seen = {}
    platform.toolchain.build = lambda *args, **kwargs: seen.update(kwargs)
    sys = ClockDomain("sys")
    require_timing(platform, {sys: 75e6})
    platform.toolchain.build(platform, None, timingstrict=False)
    assert seen["timingstrict"] is True
    assert platform.toolchain.clocks[sys.clk][0] == pytest.approx(1e3 / 75, abs=1e-3)


def test_ice40_builds_fail_when_timing_fails():
    platform = kosagi_fomu_evt.Platform()
    seen = []
    platform.toolchain.build = lambda *args, **kwargs: seen.append(kwargs)
    sys = ClockDomain("sys")
    require_timing(platform, {sys: 12e6})
    require_timing(platform, {})  # a second call wraps nothing again
    platform.toolchain.build(platform, None, timingstrict=False)
    assert seen == [{"timingstrict": True}]
    assert platform.toolchain.clocks[sys.clk][0] == pytest.approx(1e3 / 12, abs=1e-3)


def test_require_timing_leaves_vivado_alone():
    platform = digilent_arty.Platform(variant="a7-35", toolchain="vivado")
    build = platform.toolchain.build
    require_timing(platform, {ClockDomain("sys"): 75e6})
    assert platform.toolchain.build == build
    assert not platform.toolchain.clocks


class LiteEthPHYMII:  # named as LiteEth's: the helper reads the PHY's clock off its class name
    def __init__(self):
        self.crg = SimpleNamespace(cd_eth_rx=ClockDomain("eth_rx"), cd_eth_tx=ClockDomain("eth_tx"))


def _litex_boards_soc(platform, *domains):
    return SimpleNamespace(platform=platform, crg=SimpleNamespace(**{f"cd_{n}": ClockDomain(n) for n in domains}))


def test_a_litex_boards_soc_has_every_crg_domain_and_its_phy_clocks_constrained():
    platform = digilent_arty.Platform(variant="a7-35", toolchain="openxc7")
    soc = _litex_boards_soc(platform, "sys", "eth", "sys4x", "sys4x_dqs", "idelay")
    soc.ethphy = LiteEthPHYMII()
    require_litex_boards_timing(soc, 50e6)
    periods = {cd.name: platform.toolchain.clocks[cd.clk][0] for cd in vars(soc.crg).values()}
    assert periods == {"sys": 20.0, "eth": 40.0, "sys4x": 5.0, "sys4x_dqs": 5.0, "idelay": 5.0}
    assert platform.toolchain.clocks[soc.ethphy.crg.cd_eth_rx.clk][0] == 40.0
    assert platform.toolchain.clocks[soc.ethphy.crg.cd_eth_tx.clk][0] == 40.0


def test_a_crg_domain_the_helper_does_not_know_fails_the_build():
    soc = _litex_boards_soc(digilent_arty.Platform(variant="a7-35", toolchain="openxc7"), "sys", "hdmi")
    with pytest.raises(ValueError, match="clock domain hdmi"):
        require_litex_boards_timing(soc, 50e6)
