# SPDX-License-Identifier: Apache-2.0
"""The Acorn pin tables, as Markdown, from wiring.toml. gen.py writes them into generated/.

acorn-connectors.md          the Acorn's P1 and P2, pin by pin
acorn-<carrier>-<P1|P2>.md   where each wire of that cable goes on that carrier
acorn-<carrier>-<header>.md  a carrier's header, pin by pin, as printed on the board
"""

import wiring

BANNER = (
    "<!-- Generated by fpgas.online-test-designs docs/wiring/acorn/gen.py from wiring.toml. "
    "Edit wiring.toml there, not this file. -->\n\n"
)


def table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


def signal_cell(sig):
    s = wiring.SIGNALS[sig]
    if sig == "VCC":
        return f"VCC: {s['what']}, **cut, never connected**"
    if s["label"] == "GND":
        return "GND"
    std = f" ({s['standard']})" if "standard" in s else ""
    return f"{s['label']}{std}: {s['what']}"


def gpio_cell(pin):
    if "gpio" not in pin:
        return "—"
    return f"{pin['gpio']} ({pin['func']})" if "func" in pin else pin["gpio"]


def connectors():
    p1, p2 = wiring.CONNECTORS["P1"]["pins"], wiring.CONNECTORS["P2"]["pins"]
    head = ["Pin", f"P2 ({wiring.CONNECTORS['P2']['what']})", f"P1 ({wiring.CONNECTORS['P1']['what']})"]
    return table(head, [(i + 1, signal_cell(a), signal_cell(b)) for i, (a, b) in enumerate(zip(p2, p1, strict=True))])


def cable(c, connector):
    pins = wiring.CONNECTORS[connector]["pins"]
    headers = {c.wires[s][0] for s in pins if s in c.wires}
    one = next(iter(headers)) if len(headers) == 1 else None
    by_pin = {v: k for k, v in c.wires.items()}  # (header, pin) -> signal
    # other wires on the same SoC line, e.g. the blade's J2 (UART 3) and TMS (Extension Port 9), both GPIO14
    shares = {s: [x for x in c.same_gpio(*c.wires[s]) if x in by_pin] for s in pins if s in c.wires}
    head = [
        f"{connector} pin",
        "Signal",
        f"→ {c.headers[one].name} pin" if one else "→ Host pin",
        "Host name",
        "GPIO",
        "Direction",
    ]
    if c.resistors:
        head.append("Series resistor")
    if any(shares.values()):
        head.append("Same line as")
    rows = []
    for i, s in enumerate(pins):
        row = [i + 1, signal_cell(s)]
        if s not in c.wires:
            row += [
                "**cut, never connected**" if s == "VCC" else "**not connected**: cut back and insulate",
                "—",
                "—",
                "—",
            ]
        else:
            h, n = c.wires[s]
            p = c.headers[h].pins[n]
            row += [
                n if one else f"{c.headers[h].name} {n}",
                p["name"],
                gpio_cell(p),
                wiring.DIRECTION.get(wiring.SIGNALS[s].get("drive"), "—"),
            ]
        if c.resistors:
            row.append(c.resistor_value if s in c.resistors else "—")
        if any(shares.values()):
            row.append(
                ", ".join(
                    f"{wiring.SIGNALS[by_pin[x]]['label']} ({c.headers[x[0]].name} {x[1]})" for x in shares.get(s, [])
                )
                or "—"
            )
        rows.append(row)
    return table(head, rows)


def header(c, key):
    h = c.headers[key]
    by_pin = {v: k for k, v in c.wires.items()}
    rpi = any("rpi" in p for p in h.pins.values())
    same = {n: c.same_gpio(key, n) for n in h.pins}
    head = ["Pin", "Silkscreen" if key != "gpio" else "Name", "GPIO"]
    if rpi:
        head.append("Same pin on a Raspberry Pi header")
    if any(same.values()):
        head.append("Same GPIO as")
    head.append("Wire")
    rows = []
    for n in sorted(h.pins):
        p = h.pins[n]
        row = [n, p["name"], gpio_cell(p)]
        if rpi:
            row.append(p.get("rpi", "—"))
        if any(same.values()):
            row.append(", ".join(f"{c.headers[k].name} {m}" for k, m in same[n]) or "—")
        if (key, n) in by_pin:
            s = by_pin[(key, n)]
            conn = next(k for k, v in wiring.CONNECTORS.items() if s in v["pins"])
            wire = f"{conn}:{wiring.CONNECTORS[conn]['pins'].index(s) + 1} {wiring.SIGNALS[s]['label']}"
        else:
            wire = "**empty, 5 V**" if p["name"].replace(" ", "") == "5V" else "empty"
        row.append(wire)
        rows.append(row)
    return table(head, rows)


def build():
    out = {"acorn-connectors.md": BANNER + connectors()}
    for key, c in wiring.CARRIERS.items():
        for conn in wiring.CONNECTORS:
            out[f"acorn-{key}-{conn.lower()}.md"] = BANNER + cable(c, conn)
        for hk in c.headers:
            out[f"acorn-{key}-{hk}.md"] = BANNER + header(c, hk)
    return out
