# SPDX-License-Identifier: Apache-2.0
"""wiring.toml is checked on load, and the tables say what the wiring says.

Run: uv run --no-project --with pytest pytest docs/wiring/acorn
"""

import copy

import pytest
import tables
import wiring

BLADE = wiring.DATA["carriers"]["blade"]


def rejects(mutate, match):
    d = copy.deepcopy(BLADE)
    mutate(d)
    with pytest.raises(wiring.WiringError, match=match):
        wiring._carrier("blade", d)


def test_the_committed_wiring_loads():
    assert set(wiring.CARRIERS) == {"pi5", "blade"}


def test_a_wire_on_a_5v_pin_is_refused():
    rejects(lambda d: d["wires"].__setitem__("K2", ["uart", 1]), "a 5V pin")


def test_two_wires_on_one_pin_are_refused():
    rejects(lambda d: d["wires"].__setitem__("K2", ["uart", 3]), "both go to uart pin 3")


def test_a_wired_vcc_is_refused():
    rejects(lambda d: d["wires"].__setitem__("VCC", ["ext", 5]), "VCC is wired")


def test_ground_on_a_signal_pin_is_refused():
    rejects(lambda d: d["wires"].__setitem__("GND2", ["uart", 4]), r"GND2 goes to uart pin 4 \(RX\)")


def test_a_wire_outside_every_housing_is_refused():
    rejects(lambda d: d["headers"]["uart"].__setitem__("housings", [[2, 3]]), "outside every housing")


def test_a_resistor_on_an_unwired_signal_is_refused():
    rejects(lambda d: d.__setitem__("resistors", ["J5"]), "resistor listed for J5")


def test_a_pin_the_header_does_not_have_is_refused():
    rejects(lambda d: d["wires"].__setitem__("K2", ["uart", 5]), "does not list")


def test_blade_j2_shares_gpio14_with_tms_and_carries_the_resistor():
    row = next(r for r in tables.cable(wiring.CARRIERS["blade"], "P2").splitlines() if r.startswith("| 2 |"))
    assert "GPIO14" in row and "470 Ω" in row and "TMS (Extension Port 9)" in row


def test_blade_spares_are_not_connected_and_pi5_spares_are():
    blade = tables.cable(wiring.CARRIERS["blade"], "P2")
    pi5 = tables.cable(wiring.CARRIERS["pi5"], "P2")
    for ball in ("J5", "H5"):
        assert "**not connected**" in next(r for r in blade.splitlines() if f"| {ball} " in r)
        assert "**not connected**" not in next(r for r in pi5.splitlines() if f"| {ball} " in r)


def test_every_generated_table_has_the_banner():
    for name, text in tables.build().items():
        assert text.startswith("<!-- Generated by"), name


def test_jtag_pins_must_match_where_the_jtag_wires_land():
    def swap(d):
        d["wires"]["TDI"], d["wires"]["TDO"] = d["wires"]["TDO"], d["wires"]["TDI"]

    rejects(swap, "jtag_pins is 2:3:4:14, but TDI:TDO:TCK:TMS land on 3:2:4:14")
