# SPDX-License-Identifier: Apache-2.0
"""wiring.toml is checked on load, and the tables say what the wiring says.

Run: uv run --no-project --with pytest pytest docs/wiring/acorn
"""

import copy

import pytest
import tables
import wiring

BLADE = wiring.DATA["carriers"]["blade"]


def rejects(mutate, match):
    d = copy.deepcopy(BLADE)
    mutate(d)
    with pytest.raises(wiring.WiringError, match=match):
        wiring._carrier("blade", d)


def test_the_committed_wiring_loads():
    assert set(wiring.CARRIERS) == {"pi5", "blade"}


def test_a_wire_on_a_5v_pin_is_refused():
    rejects(lambda d: d["wires"].__setitem__("K2", ["uart", 1]), "a 5V pin")


def test_two_wires_on_one_pin_are_refused():
    rejects(lambda d: d["wires"].__setitem__("K2", ["uart", 3]), "both go to uart pin 3")


def test_a_wired_vcc_is_refused():
    rejects(lambda d: d["wires"].__setitem__("VCC", ["ext", 5]), "VCC is wired")


def test_ground_on_a_signal_pin_is_refused():
    rejects(lambda d: d["wires"].__setitem__("GND2", ["uart", 4]), r"GND2 goes to uart pin 4 \(RX\)")


def test_a_wire_outside_every_housing_is_refused():
    rejects(lambda d: d["headers"]["uart"].__setitem__("housings", [[2, 3]]), "outside every housing")


def test_a_resistor_on_an_unwired_signal_is_refused():
    rejects(lambda d: d.__setitem__("resistors", ["J5"]), "resistor listed for J5")


def test_a_pin_the_header_does_not_have_is_refused():
    rejects(lambda d: d["wires"].__setitem__("K2", ["uart", 5]), "does not list")


def test_blade_j2_shares_gpio14_with_tms_and_carries_the_resistor():
    row = next(r for r in tables.cable(wiring.CARRIERS["blade"], "P2").splitlines() if r.startswith("| 2 |"))
    assert "GPIO14" in row and "470 Ω" in row and "TMS (Extension Port 9)" in row


def test_blade_spares_are_not_connected_and_pi5_spares_are():
    blade = tables.cable(wiring.CARRIERS["blade"], "P2")
    pi5 = tables.cable(wiring.CARRIERS["pi5"], "P2")
    for ball in ("J5", "H5"):
        assert "**not connected**" in next(r for r in blade.splitlines() if f"| {ball} " in r)
        assert "**not connected**" not in next(r for r in pi5.splitlines() if f"| {ball} " in r)


def test_every_generated_table_has_the_banner():
    for name, text in tables.build().items():
        assert text.startswith("<!-- Generated by"), name


def test_jtag_pins_must_match_where_the_jtag_wires_land():
    def swap(d):
        d["wires"]["TDI"], d["wires"]["TDO"] = d["wires"]["TDO"], d["wires"]["TDI"]

    rejects(swap, "jtag_pins is 2:3:4:14, but TDI:TDO:TCK:TMS land on 3:2:4:14")


def _tables(key):
    """The parts table and the tools table of a carrier's list, each as its rows' cells."""
    text = tables.bom(wiring.CARRIERS[key])
    blocks = [[line for line in block.splitlines() if line.startswith("|")] for block in text.split("\n\n")]
    parts, tools = [block for block in blocks if block]
    return [[cell.strip() for cell in row.strip("|").split(" | ")] for row in parts], [
        [cell.strip() for cell in row.strip("|").split(" | ")] for row in tools
    ]


def _bom(key):
    return {r[2]: (int(r[1]), r[4]) for r in _tables(key)[0][2:]}


def test_the_parts_list_counts_housings_terminals_and_resistors_from_the_wiring():
    """The housings are the headers' own, a terminal for each connected wire, a resistor for each wire that
    has one: counted, so the list cannot say something the wiring does not."""
    blade, pi5 = _bom("blade"), _bom("pi5")
    assert blade["Dupont housing, 2×5, 2.54 mm pitch"] == (
        1,
        "over Extension Port pins 1 to 10; 5 of its 10 cavities stay empty",
    )
    assert blade["Dupont housing, 1×4, 2.54 mm pitch"] == (1, "over UART pins 1 to 4; 1 of its 4 cavities stays empty")
    assert blade["Dupont female crimp terminal, 2.54 mm"][0] == len(wiring.CARRIERS["blade"].wires) == 8
    assert blade["resistor, 470 Ω, 1/8 W axial"] == (1, "in series with J2")
    assert pi5["Dupont housing, 2×3, 2.54 mm pitch"][0] == pi5["Dupont housing, 2×4, 2.54 mm pitch"][0] == 1
    assert pi5["Dupont female crimp terminal, 2.54 mm"][0] == len(wiring.CARRIERS["pi5"].wires) == 10
    assert not [part for part in pi5 if part.startswith("resistor")]


def test_every_line_of_a_parts_list_can_be_ticked_and_names_the_cable_by_its_part_number():
    for key in wiring.CARRIERS:
        parts, tools = _tables(key)
        assert parts[0] == ["Have it", "Qty", "Part", "Part number", "What it is for"]
        assert tools[0] == ["Have it", "Tool", "What it is for"]
        assert all(row[0] == tables.TICK for row in [*parts[2:], *tools[2:]])
        assert any(row[3] == "Molex 0369200601" for row in parts[2:])


def test_a_list_says_it_is_for_one_host_and_names_the_tools_the_cables_take():
    blade, pi5 = tables.bom(wiring.CARRIERS["blade"]), tables.bom(wiring.CARRIERS["pi5"])
    assert blade.startswith("The parts for **one** Compute Blade host; for several hosts, that many of each.\n\n|")
    assert "The tools to build, fit and check its two cables, once for any number of hosts:" in blade
    tools = {row[1] for row in _tables("blade")[1][2:]}
    assert {"multimeter with a continuity buzzer", "crimping tool for 2.54 mm Dupont terminals"} <= tools
    # the iron is for the series resistor, which only the Compute Blade's wiring has
    assert "soldering iron and solder" in tools
    assert "soldering iron and solder" not in {row[1] for row in _tables("pi5")[1][2:]}
    assert pi5.startswith("The parts for **one** Raspberry Pi 5 host;")


def test_a_part_without_a_quantity_is_refused():
    rejects(lambda d: d["parts"].append({"part": "a thing"}), "a part needs a whole `qty`")
    rejects(lambda d: d["parts"].append({"qty": 1, "part": "a thing", "price": 3}), "keys other than")


HAT_NAME = "Waveshare PoE M.2 HAT+ (B)"


def test_the_pictures_draw_the_poe_m2_hat_plus_b_and_it_takes_the_acorn():
    # Tim, 7 October 2026: only the (B) is drawn. The PoE M.2 HAT+ without the (B) takes 2230 and 2242 cards only.
    hat = wiring.CARRIERS["pi5"].hat
    assert hat.name == hat.product == HAT_NAME
    assert hat.page == "https://www.waveshare.com/poe-m.2-hat-plus-b.htm"
    assert "PoE-M.2-HAT-Plus-B" in hat.drawing and hat.photo == "hat-plus-b-ccw.jpg"
    assert hat.largest_card == "2280" and "2280" in next(
        p["note"] for p in wiring.DATA["parts"] if "Acorn" in p["part"]
    )
    assert wiring.CARRIERS["blade"].hat is None


def test_every_pi5_page_and_picture_names_the_hat_and_none_names_another():
    import re

    import gen

    pi5 = {n: t for n, t in gen.build().items() if "pi5" in n}
    for name in ("acorn-pi5-bom.md", "acorn-build-pi5-overview.md", "acorn-cables-pi5.md"):
        assert HAT_NAME in pi5[name], name
    for name in (
        "acorn-wiring-pi5.svg",
        "acorn-cable-pi5-p1.svg",
        "acorn-cable-pi5-p2.svg",
        "acorn-cable-pi5-fit-2.svg",
    ):
        said = re.findall(r'aria-label="([^"]*)"', pi5[name])  # the words drawn, each line of text once
        assert any("HAT+ (B)" in line for line in said), name
    # "HAT+" alone is the other HAT, named only to say it is not this guide's
    for name, text in pi5.items():
        for m in re.finditer(r"HAT\+(?! \(B\))", text):
            assert "without the (B)" in text[m.start() : m.end() + 40], (name, text[m.start() - 60 : m.end() + 40])


@pytest.mark.parametrize("field", wiring.HAT_FIELDS)
def test_a_hat_that_lacks_a_field_is_refused(field):
    raw = copy.deepcopy(wiring.DATA["carriers"]["pi5"])
    del raw["hat"][field]
    with pytest.raises(wiring.WiringError, match=f"the hat table lacks \\['{field}'\\]"):
        wiring._carrier("pi5", raw)


def test_no_part_naming_the_hat_is_refused():
    raw = copy.deepcopy(wiring.DATA["carriers"]["pi5"])
    raw["parts"] = [p for p in raw["parts"] if HAT_NAME not in p["part"]]
    with pytest.raises(wiring.WiringError, match="no part names the HAT"):
        wiring._carrier("pi5", raw)


def test_where_things_are_in_the_hat_photo_is_what_measure_hat_measures():
    import measure_hat

    hat = wiring.DATA["carriers"]["pi5"]["hat"]
    got = measure_hat.measure(wiring.HERE / "photos" / hat["photo"])
    assert {k: hat[k] for k in measure_hat.STORED} == {k: got[k] for k in measure_hat.STORED}


def test_the_hat_in_geometry_toml_is_what_measure_hat_measures():
    import measure_hat
    import tomllib

    hat = tomllib.loads((wiring.HERE / "geometry.toml").read_text())["things"]["hat"]
    photo = wiring.DATA["carriers"]["pi5"]["hat"]["photo"]
    got = measure_hat.measure_mm(wiring.HERE / "photos" / photo)
    assert hat["size"] == got["size"]
    assert hat["photos"]["top"]["px_per_mm"] == got["px_per_mm"] and hat["photos"]["top"]["origin"] == got["origin"]
    assert hat["headers"]["header"]["pin1"] == got["pin1"]
    assert hat["items"]["m2-slot"]["box"] == got["m2_slot"]
