# SPDX-License-Identifier: Apache-2.0
"""The pieces every generated Markdown fragment is made of."""


def banner(generator):
    """The first line of a generated file: which generator wrote it, and where to change it instead.

    `generator` is the generator's directory under docs/wiring/, such as "acorn".
    """
    return (
        f"<!-- Generated by fpgas.online-test-designs docs/wiring/{generator}/gen.py from wiring.toml. "
        "Edit wiring.toml there, not this file. -->\n\n"
    )


def table(head, rows):
    """A Markdown table: `head` the column names, `rows` a list of rows of cells."""
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"
